# Generated by Django 4.2 on 2023-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='static/profile_pic/features-first-icon.png', null=True, upload_to='static/team_pic/')),
                ('Social_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('Social_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('Social_whatsapp', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
