# Generated by Django 4.2 on 2023-05-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='Social_instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
