# Generated by Django 4.2 on 2023-04-28 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.make')),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/sparepart_images')),
                ('car_models', models.ManyToManyField(to='products.model')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.partcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('usednew', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.PositiveIntegerField()),
                ('car_price', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mileage', models.PositiveIntegerField()),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('power', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_seats', models.CharField(blank=True, max_length=50, null=True)),
                ('doors', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('vehicle_extras', models.TextField(blank=True, max_length=200, null=True)),
                ('image_1', models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/')),
                ('image_2', models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/')),
                ('image_3', models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/')),
                ('featured', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='products.model')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
