# Generated by Django 4.2 on 2023-05-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_extras',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
