# Generated by Django 4.2 on 2023-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_car_vehicle_extras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['created']},
        ),
    ]
