# Generated by Django 4.2 on 2023-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_car_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='car_models',
        ),
    ]
