# Generated by Django 4.2 on 2023-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_part_car_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
