# Generated by Django 4.2 on 2023-05-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_part_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_price',
        ),
    ]
