# Generated by Django 4.2 on 2023-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_car_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
