# Generated by Django 4.2 on 2023-05-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_car_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
