# Generated by Django 4.2 on 2023-05-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_part_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-created']},
        ),
    ]
