# Generated by Django 4.2 on 2023-07-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_car_options_alter_part_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vehicle_extras',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
