# Generated by Django 4.2 on 2023-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_car_color_remove_car_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_10',
            field=models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_4',
            field=models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_5',
            field=models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_6',
            field=models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_7',
            field=models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_8',
            field=models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_9',
            field=models.ImageField(blank=True, default='static/cars_pic/features-first-icon.png', null=True, upload_to='static/cars_pic/'),
        ),
    ]
