# Generated by Django 4.2 on 2023-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_car_image_10_car_image_4_car_image_5_car_image_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='page_visits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
