# Generated by Django 4.2 on 2024-03-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_car_page_visits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-page_visits']},
        ),
    ]
